"""consentimento lgpd

Revisão: 26f115c17c37
Revisão anterior: 84abd4a3558a
Criada em: 2026-08-21 16:39:44.239045
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '26f115c17c37'
down_revision = '84abd4a3558a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('versao_do_termo', sa.String(length=20), nullable=False),
    sa.Column('aceito_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consentimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentimento_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consentimento_versao_do_termo'), ['versao_do_termo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consentimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentimento_versao_do_termo'))
        batch_op.drop_index(batch_op.f('ix_consentimento_usuario_id'))

    op.drop_table('consentimento')
    # ### end Alembic commands ###
