"""esquema inicial

Revisão: 84abd4a3558a
Revisão anterior: 
Criada em: 2026-08-21 16:16:42.861846
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '84abd4a3558a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=40), nullable=False),
    sa.Column('equipamento', sa.String(length=40), nullable=False),
    sa.Column('composto', sa.Boolean(), nullable=False),
    sa.Column('convencao_de_carga', sa.Enum('TOTAL', 'POR_HALTER', 'PESO_CORPORAL', name='convencaodecarga', native_enum=False), nullable=False),
    sa.Column('incremento_kg', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercicio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercicio_grupo_muscular'), ['grupo_muscular'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercicio_nome'), ['nome'], unique=True)

    op.create_table('tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('escopo', sa.Enum('EXECUCAO', 'INTRA_SERIE', 'AGRUPAMENTO', name='escopodatecnica', native_enum=False), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('distorce_estimativa', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tecnica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tecnica_escopo'), ['escopo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tecnica_nome'), ['nome'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('TREINADOR', 'ALUNO', name='papel', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('treinador_id', sa.Integer(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', 'OUTRO', name='sexo', native_enum=False), nullable=True),
    sa.Column('altura_cm', sa.Float(), nullable=True),
    sa.Column('objetivo', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['treinador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aluno_treinador_id'), ['treinador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aluno_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('checkin_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('horas_de_sono', sa.Float(), nullable=True),
    sa.Column('passos_por_dia', sa.Integer(), nullable=True),
    sa.Column('qualidade_do_sono', sa.Integer(), nullable=True),
    sa.Column('disposicao', sa.Integer(), nullable=True),
    sa.Column('recuperacao', sa.Integer(), nullable=True),
    sa.Column('aderencia_dieta', sa.Integer(), nullable=True),
    sa.Column('aderencia_treino', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'semana', name='um_checkin_por_semana')
    )
    with op.batch_alter_table('checkin_semanal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_semanal_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_semanal_semana'), ['semana'], unique=False)

    op.create_table('periodizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('objetivo', sa.String(length=200), nullable=True),
    sa.Column('fase', sa.Enum('ACUMULACAO', 'INTENSIFICACAO', 'PICO', 'DELOAD', 'MANUTENCAO', name='fasedaperiodizacao', native_enum=False), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=True),
    sa.Column('semanas', sa.Integer(), nullable=False),
    sa.Column('equacao', sa.String(length=20), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('periodizacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periodizacao_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('medida_corporal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('cintura_cm', sa.Float(), nullable=True),
    sa.Column('quadril_cm', sa.Float(), nullable=True),
    sa.Column('torax_cm', sa.Float(), nullable=True),
    sa.Column('braco_cm', sa.Float(), nullable=True),
    sa.Column('coxa_cm', sa.Float(), nullable=True),
    sa.Column('panturrilha_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkin_semanal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medida_corporal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medida_corporal_checkin_id'), ['checkin_id'], unique=True)

    op.create_table('sessao_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodizacao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('dia_da_semana', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['periodizacao_id'], ['periodizacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessao_modelo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_modelo_periodizacao_id'), ['periodizacao_id'], unique=False)

    op.create_table('prescricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessao_modelo_id', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('bloco', sa.String(length=4), nullable=True),
    sa.Column('agrupamento_id', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=False),
    sa.Column('reps_max', sa.Integer(), nullable=False),
    sa.Column('rir_alvo', sa.Integer(), nullable=True),
    sa.Column('descanso_s', sa.Integer(), nullable=True),
    sa.Column('carga_alvo_kg', sa.Float(), nullable=True),
    sa.Column('percentual_1rm', sa.Float(), nullable=True),
    sa.Column('cadencia', sa.String(length=15), nullable=True),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['agrupamento_id'], ['tecnica.id'], ),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['sessao_modelo_id'], ['sessao_modelo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricao_exercicio_id'), ['exercicio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricao_sessao_modelo_id'), ['sessao_modelo_id'], unique=False)

    op.create_table('prescricao_tecnica',
    sa.Column('prescricao_id', sa.Integer(), nullable=False),
    sa.Column('tecnica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnica.id'], ),
    sa.PrimaryKeyConstraint('prescricao_id', 'tecnica_id')
    )
    op.create_table('serie_da_prescricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescricao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('carga_kg', sa.Float(), nullable=True),
    sa.Column('carga_ate_kg', sa.Float(), nullable=True),
    sa.Column('tipo', sa.Enum('AQUECIMENTO', 'UP_SET', 'VALIDA', 'BACK_OFF', name='tipodeserie', native_enum=False), nullable=False),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serie_da_prescricao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serie_da_prescricao_prescricao_id'), ['prescricao_id'], unique=False)

    op.create_table('serie_tecnica',
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('tecnica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['serie_da_prescricao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnica.id'], ),
    sa.PrimaryKeyConstraint('serie_id', 'tecnica_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie_tecnica')
    with op.batch_alter_table('serie_da_prescricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serie_da_prescricao_prescricao_id'))

    op.drop_table('serie_da_prescricao')
    op.drop_table('prescricao_tecnica')
    with op.batch_alter_table('prescricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricao_sessao_modelo_id'))
        batch_op.drop_index(batch_op.f('ix_prescricao_exercicio_id'))

    op.drop_table('prescricao')
    with op.batch_alter_table('sessao_modelo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_modelo_periodizacao_id'))

    op.drop_table('sessao_modelo')
    with op.batch_alter_table('medida_corporal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medida_corporal_checkin_id'))

    op.drop_table('medida_corporal')
    with op.batch_alter_table('periodizacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periodizacao_aluno_id'))

    op.drop_table('periodizacao')
    with op.batch_alter_table('checkin_semanal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_semanal_semana'))
        batch_op.drop_index(batch_op.f('ix_checkin_semanal_aluno_id'))

    op.drop_table('checkin_semanal')
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aluno_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_aluno_treinador_id'))

    op.drop_table('aluno')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('tecnica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tecnica_nome'))
        batch_op.drop_index(batch_op.f('ix_tecnica_escopo'))

    op.drop_table('tecnica')
    with op.batch_alter_table('exercicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercicio_nome'))
        batch_op.drop_index(batch_op.f('ix_exercicio_grupo_muscular'))

    op.drop_table('exercicio')
    # ### end Alembic commands ###
