"""protocolo alimentar

Revisão: aa768c4e9348
Revisão anterior: 26f115c17c37
Criada em: 2026-08-21 17:13:14.685531
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'aa768c4e9348'
down_revision = '26f115c17c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('fonte', sa.String(length=30), nullable=False),
    sa.Column('codigo_de_barras', sa.String(length=20), nullable=True),
    sa.Column('kcal_100g', sa.Float(), nullable=True),
    sa.Column('proteina_100g', sa.Float(), nullable=True),
    sa.Column('carboidrato_100g', sa.Float(), nullable=True),
    sa.Column('gordura_100g', sa.Float(), nullable=True),
    sa.Column('fibra_100g', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alimento_codigo_de_barras'), ['codigo_de_barras'], unique=False)
        batch_op.create_index(batch_op.f('ix_alimento_nome'), ['nome'], unique=False)

    op.create_table('protocolo_alimentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('kcal_alvo', sa.Integer(), nullable=True),
    sa.Column('deficit_kcal', sa.Integer(), nullable=True),
    sa.Column('proteina_g', sa.Integer(), nullable=True),
    sa.Column('carboidrato_g', sa.Integer(), nullable=True),
    sa.Column('gordura_g', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocolo_alimentar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocolo_alimentar_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('grupo_de_substituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo_alimentar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupo_de_substituicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupo_de_substituicao_protocolo_id'), ['protocolo_id'], unique=False)

    op.create_table('refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo_alimentar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refeicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refeicao_protocolo_id'), ['protocolo_id'], unique=False)

    op.create_table('suplemento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('dose', sa.String(length=80), nullable=True),
    sa.Column('momento', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo_alimentar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suplemento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suplemento_protocolo_id'), ['protocolo_id'], unique=False)

    op.create_table('aderencia_da_refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('refeicao_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('seguiu', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refeicao_id'], ['refeicao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'refeicao_id', 'dia', name='uma_marcacao_por_refeicao_por_dia')
    )
    with op.batch_alter_table('aderencia_da_refeicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aderencia_da_refeicao_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aderencia_da_refeicao_dia'), ['dia'], unique=False)
        batch_op.create_index(batch_op.f('ix_aderencia_da_refeicao_refeicao_id'), ['refeicao_id'], unique=False)

    op.create_table('item_da_refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refeicao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('a_gosto', sa.Boolean(), nullable=False),
    sa.Column('opcional', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_de_substituicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refeicao_id'], ['refeicao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_da_refeicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_da_refeicao_refeicao_id'), ['refeicao_id'], unique=False)

    op.create_table('item_de_substituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('alimento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimento.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_de_substituicao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_de_substituicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_de_substituicao_grupo_id'), ['grupo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_de_substituicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_de_substituicao_grupo_id'))

    op.drop_table('item_de_substituicao')
    with op.batch_alter_table('item_da_refeicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_da_refeicao_refeicao_id'))

    op.drop_table('item_da_refeicao')
    with op.batch_alter_table('aderencia_da_refeicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aderencia_da_refeicao_refeicao_id'))
        batch_op.drop_index(batch_op.f('ix_aderencia_da_refeicao_dia'))
        batch_op.drop_index(batch_op.f('ix_aderencia_da_refeicao_aluno_id'))

    op.drop_table('aderencia_da_refeicao')
    with op.batch_alter_table('suplemento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suplemento_protocolo_id'))

    op.drop_table('suplemento')
    with op.batch_alter_table('refeicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refeicao_protocolo_id'))

    op.drop_table('refeicao')
    with op.batch_alter_table('grupo_de_substituicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupo_de_substituicao_protocolo_id'))

    op.drop_table('grupo_de_substituicao')
    with op.batch_alter_table('protocolo_alimentar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocolo_alimentar_aluno_id'))

    op.drop_table('protocolo_alimentar')
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alimento_nome'))
        batch_op.drop_index(batch_op.f('ix_alimento_codigo_de_barras'))

    op.drop_table('alimento')
    # ### end Alembic commands ###
