"""senha alterada em

Revisão: fd9bec969f00
Revisão anterior: aa768c4e9348
Criada em: 2026-08-21 17:53:03.652600
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fd9bec969f00'
down_revision = 'aa768c4e9348'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # As duas colunas são NOT NULL, então precisam de `server_default`: sem ele
    # o ALTER quebra em qualquer banco que já tenha uma conta dentro — que é
    # justamente o banco onde esta migração vai rodar.
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "senha_alterada_em",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("CURRENT_TIMESTAMP"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "senha_provisoria",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # Toda conta de aluno que já existe teve a senha definida pelo treinador —
    # foi ele quem a cadastrou. Marcá-las é o que é verdade, e é o que faz o
    # app pedir a troca a quem ainda usa a senha que outra pessoa escolheu.
    op.execute("UPDATE usuario SET senha_provisoria = 1 WHERE papel = 'aluno'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('senha_provisoria')
        batch_op.drop_column('senha_alterada_em')

    # ### end Alembic commands ###
