"""treino executado

Revisão: fedcf67fd49c
Revisão anterior: fd9bec969f00
Criada em: 2026-08-21 18:23:23.608684
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fedcf67fd49c'
down_revision = 'fd9bec969f00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessao_realizada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao_modelo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'sessao_id', 'dia', name='um_treino_por_dia')
    )
    with op.batch_alter_table('sessao_realizada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_realizada_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessao_realizada_dia'), ['dia'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessao_realizada_sessao_id'), ['sessao_id'], unique=False)

    op.create_table('serie_realizada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessao_realizada_id', sa.Integer(), nullable=False),
    sa.Column('chave_local', sa.String(length=64), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('prescricao_id', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('carga_kg', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('AQUECIMENTO', 'UP_SET', 'VALIDA', 'BACK_OFF', name='tipodeserie', native_enum=False), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('registrada_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicio.id'], ),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serie_id'], ['serie_da_prescricao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sessao_realizada_id'], ['sessao_realizada.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sessao_realizada_id', 'chave_local', name='uma_serie_por_chave')
    )
    with op.batch_alter_table('serie_realizada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serie_realizada_exercicio_id'), ['exercicio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serie_realizada_sessao_realizada_id'), ['sessao_realizada_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie_realizada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serie_realizada_sessao_realizada_id'))
        batch_op.drop_index(batch_op.f('ix_serie_realizada_exercicio_id'))

    op.drop_table('serie_realizada')
    with op.batch_alter_table('sessao_realizada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_realizada_sessao_id'))
        batch_op.drop_index(batch_op.f('ix_sessao_realizada_dia'))
        batch_op.drop_index(batch_op.f('ix_sessao_realizada_aluno_id'))

    op.drop_table('sessao_realizada')
    # ### end Alembic commands ###
